package com.aitrade.ui

import android.view.View
import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.remember
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.platform.LocalConfiguration
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.unit.LayoutDirection
import androidx.compose.ui.unit.LocalLayoutDirection
import com.aitrade.data.localizedTo

/**
 * Langues de l'interface.
 *
 * Aucun drapeau en emoji : un drapeau n'est pas une langue (celui des États-Unis
 * pour l'anglais, du Brésil pour le portugais, d'Arabie saoudite pour l'arabe),
 * et un emoji ne tient pas le rôle d'une icône. Le code (`FR`, `EN`…) dit la
 * même chose sans ambiguïté, et il est déjà affiché à côté dans la barre du
 * haut.
 */
enum class AppLanguage(
    val code: String,
    val displayName: String,
) {
    FRENCH("fr", "Français"),
    ENGLISH("en", "English"),
    SPANISH("es", "Español"),
    GERMAN("de", "Deutsch"),
    CHINESE("zh", "中文"),
    ARABIC("ar", "العربية"),
    JAPANESE("ja", "日本語"),
    PORTUGUESE("pt", "Português"),
    RUSSIAN("ru", "Русский"),
    HINDI("hi", "हिन्दी"),
    ;

    companion object {
        fun fromCode(code: String): AppLanguage = entries.find { it.code.equals(code, ignoreCase = true) } ?: FRENCH
    }
}

data class AppStrings(
    val appTitle: String,
    val paperBalance: String,
    val tabTerminal: String,
    val tabInsights: String,
    val tabRisk: String,
    val tabChat: String,
    val tabCloud: String,
    val engineActive: String,
    val engineStopped: String,
    val startBot: String,
    val stopBot: String,
    val watchlistTitle: String,
    val syncRates: String,
    val chartTitle: String,
    val signalsTitle: String,
    val noSignalsYet: String,
    val buy: String,
    val sell: String,
    val statusExecuted: String,
    val statusPending: String,
    val statusBlockedRisk: String,
    val insightsTitle: String,
    val scanNewsBtn: String,
    val scanningNews: String,
    val multiBrokerTitle: String,
    val multiBrokerSubtitle: String,
    val activeBroker: String,
    val selectBroker: String,
    val saveBrokerConfig: String,
    val simulationMode: String,
    val liveModeWarning: String,
    val languageSettingsTitle: String,
    val languageSettingsSubtitle: String,
    val riskSettingsTitle: String,
    val riskPctLabel: String,
    val minConfidenceLabel: String,
    val maxDailyLossLabel: String,
    val maxDrawdownLabel: String,
    val maxOpenTradesLabel: String,
    val saveRiskBtn: String,
    val logTerminalTitle: String,
    val clearLogsBtn: String,
    val aiChatTitle: String,
    val aiChatSubtitle: String,
    val chatPlaceholder: String,
    val sendBtn: String,
    val vipCloudTitle: String,
    val vipCloudSubtitle: String,
    val syncNowBtn: String,
    val portfolioPerformanceTitle: String,
    val portfolioPerformanceSubtitle: String,
    val totalEquity: String,
    val realizedPnl: String,
    val winRate: String,
    val totalTrades: String,
    val entryLabel: String,
    val stopLossLabel: String,
    val takeProfitLabel: String,
    val confidenceLabel: String,
    val priceLabel: String,
    val noLogsYet: String,
    val runGeminiAnalysis: String,
    val noInsightsYet: String,
    val currentEquityLabel: String,
    val maxDrawdownLimitLabel: String,
    val currentDrawdownLabel: String,
    val saveRiskParameters: String,
    val configuringBroker: String,
    val serverGatewayUrlLabel: String,
    val saveBrokerConfiguration: String,
    val resetEntireTradingData: String,
    val vipFeatureLockedTitle: String,
    val searchGroundingLabel: String,
    val mapsLocatorLabel: String,
    val deepReasoningLabel: String,
    val flashModeLabel: String,
    val chatInputPlaceholder: String,
    val quantBacktestTitle: String,
    val quantBacktestSubtitle: String,
    val strategyReturn: String,
    val benchmarkReturn: String,
    val sharpeRatio: String,
    val profitFactor: String,
    val maxDrawdown: String,
    val systemHealthTitle: String,
    val resetCircuitBreaker: String,
    val workerQueueThroughput: String,
    val jobsProcessed: String,
    val memoryUsage: String,
    val brokerState: String,
    val quantMemoryTitle: String,
    val quantMemorySubtitle: String,
    val bestRegime: String,
    val aiAccuracy: String,
    val payWithPaypal: String,
    val googlePaySandbox: String,
    val cancelBtn: String,
    val firebaseAuthTitle: String,
    val signInWithGoogle: String,
    val signOutFromFirebase: String,
    val firestoreDbSyncTitle: String,
    val eliteVipLicenseTitle: String,
    val activateVipSub: String,
    val demoAccount: String,
    val demoBalance: String,
    val resetDemoCapital: String,
    val setInitialCapital: String,
    val updateDemoCapitalBtn: String,
    val manageDemoAccount: String,
    val liveBrokerAccount: String,
    val geminiParametersTitle: String,
    val vipLockedText: String,
    val institutionalGradeTitle: String,
    val monthlyVip: String,
    val annualVip: String,
    val lifetimeElite: String,
    val bestValue: String,
    val payPalSupported: String,
    val vipActiveBadge: String,
    val dangerZone: String,
    val keysConfiguredLabel: String,
    val connectedStatusLabel: String,
    val disconnectedStatusLabel: String,
    val syncedStatusLabel: String,
    val outOfSyncStatusLabel: String,
    val paperSimLabel: String,
    val liveTradingLabel: String,
    val okBtn: String,
    val activeLabel: String,
    val vipProLabel: String,
    val freeLabel: String,
    val geminiBias: String,
    val bullishLabel: String,
    val bearishLabel: String,
    val neutralLabel: String,
    val scoreLabel: String,
    val geopoliticalLabel: String,
    val sentimentLabel: String,
    val biasImpactLabel: String,
    val scanningMetrics: String,
    val vipFeature1: String,
    val vipFeature2: String,
    val vipFeature3: String,
    val vipFeature4: String,
    val chatWelcomeMessage: String,
    val chatSend: String,
    val chatClear: String,
    val chatSenderUser: String,
    val chatSenderGemini: String,
    val chatLockedBody: String,
    val chatAttachedPattern: String,
    val chatSearchGroundingFull: String,
    val chatMapsGroundingFull: String,
    val chatHighThinkingMode: String,
    val insightsErrorAnalysis: String,
    val backtestStrategyMode: String,
    val backtestMonteCarloStress: String,
    val backtestTradeLogs: String,
    val backtestBtcBenchmark: String,
    val backtestAlpha: String,
    val backtestBeta: String,
    val backtestSharpe: String,
    val backtestSortino: String,
    val backtestCalmar: String,
    val backtestMaxDd: String,
    val monteCarloTitle: String,
    val monteCarloVar95: String,
    val monteCarloVar99: String,
    val monteCarloVarAt95: String,
    val monteCarloCvar: String,
    val monteCarloMedianEquity: String,
    val chartScannerTitle: String,
    val chartScannerSelect: String,
    val chartPatternDoubleBottom: String,
    val chartPatternHeadShoulders: String,
    val chartPatternHs: String,
    val chartPatternRsiDivergence: String,
    val agentDeskTitle: String,
    val agentDeskSubtitle: String,
    val agentConsensus: String,
    val agentCoordinating: String,
    val agentRunResearch: String,
    val agentTargetAsset: String,
    val agentConfidence: String,
    val agentEntry: String,
    val agentStopLoss: String,
    val agentTakeProfit: String,
    val agentCioSynthesis: String,
    val agentInjectSignal: String,
    val portfolioStartingCapital: String,
    val portfolioCurrentEquity: String,
    val portfolioPoint: String,
    val portfolioPnl: String,
    val portfolioFilterAll: String,
    val portfolioFilterYtd: String,
    val tradeLogHistory: String,
    val tradeLogEntry: String,
    val vipPaypalActive: String,
    val vipPlanMonthly: String,
    val vipPlanAnnual: String,
    val vipPlanLifetime: String,
    val vipStandardAccess: String,
    val vipSaveAnnual: String,
    val vipPayOnce: String,
    val vipInstitutionalUnlocked: String,
    val vipLicenseActive: String,
    val vipAllFeaturesActive: String,
    val gpayTitle: String,
    val gpayUpgradePlan: String,
    val gpayTotalCharge: String,
    val gpayMerchantNote: String,
    val gpayAuthorizing: String,
    val gpayCreditCard: String,
    val gpayPaypalLogo: String,
    val firebaseAuthNote: String,
    val firestoreConnectBtn: String,
    val firestoreSyncNote: String,
    val firestoreSyncedLabel: String,
    val firestoreOutOfSyncLabel: String,
    val learnTitle: String,
    val learnSubtitle: String,
    val learnReevaluate: String,
    val learnWeightsAdjusted: String,
    val learnWeightTa: String,
    val learnWeightMacro: String,
    val learnWeightSentiment: String,
    val learnRulesGenerated: String,
    val learnPostMortemLessons: String,
    val execModeLiveTitle: String,
    val execModePaperTitle: String,
    val execLiveNote: String,
    val execPaperNote: String,
    val execSwitchPaper: String,
    val execSwitchLive: String,
    val healthBrokerPaperSandbox: String,
    val healthBrokerAlpacaPaper: String,
    val healthBrokerAlpacaLive: String,
    val healthBrokerUnknown: String,
    val brokerQuickConnect: String,
    val brokerExecutesSimulated: String,
    val brokerWebhookToken: String,
    val brokerPasswordSecret: String,
    val brokerApiKeyOf: String,
    val brokerApiSecretOf: String,
    val brokerDescStocksCrypto: String,
    val brokerDescGlobalEquities: String,
    val brokerDescPropFirm: String,
    val brokerDescRawSpreads: String,
    val brokerDescStp: String,
    val brokerDescEcn: String,
    val brokerDescMicro: String,
    val brokerDescLeverage: String,
    val brokerDescDma: String,
    val brokerDescFixedFloating: String,
    val brokerDescMultiAsset: String,
    val brokerDescForexCommodities: String,
    val brokerDescCryptoSpotDerivatives: String,
    val brokerDescCryptoSpotFutures: String,
    val brokerDescProprietary: String,
    val brokerNameAlpaca: String,
    val brokerNameIbkr: String,
    val brokerNameFtmo: String,
    val brokerNameIcmarkets: String,
    val brokerNamePepperstone: String,
    val brokerNameRoboforex: String,
    val brokerNameXm: String,
    val brokerNameExness: String,
    val brokerNameFpmarkets: String,
    val brokerNameAvatrade: String,
    val brokerNameAdmirals: String,
    val brokerNameOanda: String,
    val brokerNameBinance: String,
    val brokerNameCoinbase: String,
    val brokerNameKraken: String,
    val brokerNameCustom: String,
    val brokerNameCustomShort: String,
    val brokerNameMetatrader: String,
    val signalTaSummary: String,
    val signalSentiment: String,
    val statusClosed: String,
    val actionStrongBuy: String,
    val actionNeutralHold: String,
    val actionStrongSell: String,
    val convictionHigh: String,
    val convictionMedium: String,
    val convictionLow: String,
    val portfolioVsBaseline: String,
    val portfolioFilter1w: String,
    val portfolioFilter1m: String,
    val priceHistoryPairTitle: String,
    val quantMemoryStats: String,
    val healthMemoryMb: String,
    val brokerAccountIdOf: String,
    val dateTimePatternShort: String,
    val vipPriceMonthly: String,
    val vipPriceAnnual: String,
    val vipPriceLifetime: String,
    val vipPeriodMonthly: String,
    val vipPeriodAnnual: String,
    val learnRuleRsiOverbought: String,
    val learnRuleHighImpactNews: String,
    val learnFeedbackActive: String,
    val logSelfLearningReview: String,
    val logBacktestSummary: String,
    val logBacktestSynthetic: String,
    val insightMultiAgentTitle: String,
    val logMultiAgentResearch: String,
    val logConsensusInjected: String,
    val logCircuitBreakerReset: String,
    val logLoopPaused: String,
    val logLoopStarted: String,
    val logLoopQueueStarted: String,
    val logPortfolioRiskBreach: String,
    val logBootstrapSignal: String,
    val logCycleScan: String,
    val logLoopError: String,
    val logPositionClosedSl: String,
    val logPositionClosedTp: String,
    val logTenantBreach: String,
    val logOrderExecuted: String,
    val logSignalBlocked: String,
    val logRiskUpdated: String,
    val logWatchlistUpdated: String,
    val logLanguageUpdated: String,
    val logBrokerSaved: String,
    val modePaper: String,
    val modeLive: String,
    val logSwitchedLive: String,
    val logSwitchedPaper: String,
    val logDemoReset: String,
    val logDemoBalanceSet: String,
    val insightSentimentApiTitle: String,
    val logSentimentApiDone: String,
    val errorParsing: String,
    val errorNullResponse: String,
    val directionBullish: String,
    val directionBearish: String,
    val directionNeutral: String,
    val insightSimulatedReasoning: String,
    val insightSentimentSimulatorTitle: String,
    val logSentimentFallbackDone: String,
    val logFirebaseSignedIn: String,
    val logFirebaseSignedOut: String,
    val errorFirestoreUnauthenticated: String,
    val logFirestoreSynced: String,
    val logVipActivated: String,
    val chatAnalyzingImage: String,
    val chatSimFallbackHeader: String,
    val chatSimImageDone: String,
    val chatSimImageAnalysis: String,
    val chatSimImageReco: String,
    val chatSimRegarding: String,
    val chatSimIntro: String,
    val chatSimBulletVolume: String,
    val chatSimBulletModes: String,
    val signalReasonBlockedByRisk: String,
    val adminOpenButton: String,
    val adminScreenTitle: String,
    val adminScreenIntro: String,
    val adminCloseButton: String,
    val adminConfigTitle: String,
    val adminBaseUrlLabel: String,
    val adminApiKeyLabel: String,
    val adminConfigNote: String,
    val adminSaveEndpoint: String,
    val adminCheckTitle: String,
    val adminCheckButton: String,
    val adminNotConfigured: String,
    val adminRoundtripTitle: String,
    val adminRoundtripNote: String,
    val adminRoundtripTablesLabel: String,
    val adminRoundtripButton: String,
    val adminRoundtripConfirmTitle: String,
    val adminRoundtripConfirmBody: String,
    val adminRoundtripConfirmWrite: String,
    val adminReportTitle: String,
    val adminReportPassed: String,
    val adminReportFailed: String,
    val adminCheckOk: String,
    val adminCheckFailed: String,
    val adminReportSelection: String,
    val adminReportWrites: String,
    val adminReportLeftovers: String,
    val adminReportNone: String,
    val adminReportCommand: String,
    val adminErrorTitle: String,
    val adminErrorBadUrl: String,
    val adminErrorRefused: String,
    val adminErrorUnreachable: String,
)

/**
 * Fournit les chaînes **et** le contexte localisé : tous les descendants lisent
 * la bonne langue, y compris via `stringResource(...)`.
 *
 * Le sens de lecture (RTL pour l'arabe) est propagé en même temps que la
 * configuration, pour que la mise en page suive la langue.
 */
@Composable
fun ProvideAppStrings(
    languageCode: String,
    content: @Composable () -> Unit,
) {
    val base = LocalContext.current
    val localized = remember(base, languageCode) { base.localizedTo(languageCode) }
    val strings = remember(localized) { appStrings(localized) }
    val configuration = localized.resources.configuration
    val layoutDirection =
        if (configuration.layoutDirection == View.LAYOUT_DIRECTION_RTL) {
            LayoutDirection.Rtl
        } else {
            LayoutDirection.Ltr
        }
    CompositionLocalProvider(
        LocalContext provides localized,
        LocalConfiguration provides configuration,
        LocalLayoutDirection provides layoutDirection,
        LocalAppStrings provides strings,
        content = content,
    )
}

val LocalAppStrings = staticCompositionLocalOf<AppStrings> {
    error("LocalAppStrings absent : entourer l'écran avec ProvideAppStrings(languageCode) { ... }")
}
